name: Go Installation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        run: |
          chmod +x /go.sh
          ./go.sh

      - name: Verify Go installation
        run: go version

      # Continue with your workflow steps...
