name: Go Installation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Go installation
        run: go version
              
      - name: Verify Go installation
        run: go install github.com/swaggo/swag/cmd/swag@latest
      # Continue with your workflow steps...
