name: Run Shell Script
on:
  push:
    branches:
      - main  # Change this to match your branch name or specify 'master' for the default branch

jobs:
  run-script:
    runs-on: ubuntu-latest  # Change the runner platform if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shell Script
        run: |
          chmod +x script.sh
          ./script.sh
